[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Web Framework:
axum = { version = "0.7.5", features = ["http2"] }
axum-core = "0.4.3"
axum-extra = {version="0.9.3", features = ["cookie-private", "query", "cookie", "cookie-signed", "typed-header"]}
cookie = "0.18"
reqwest = { version = "0.12.2", features = ["json"] }

# Auth:
oauth2 = "4.4.2"
jsonwebtoken = "9.3.0"

# Middleware:
tower = { version = "0.4.13", features = ["util", "timeout"] }
tower-http = { version = "0.5.2", features = ["cors", "fs", "trace"] }

# Database:
sqlx = { version = "0.7.4", features = ["runtime-tokio", "macros", "uuid", "json", "chrono", "migrate", "postgres"] }

# Async Runtime:
tokio = { version = "1.37.0", features = ["full"] }
tokio-postgres = "0.7.10"

# Logging:
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# Metrics
axum-prometheus = "0.6.1"

# Environment variables:
envy = "0.4.2"

# Serialisation/Deserialisation:
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"

# Validation:
axum-valid = "0.17.0"
validator = { version = "0.17.0", features = ["derive"] }

# Time:
chrono = { version = "0.4.37", features = ["clock", "serde"] }
time = "0.3.34"

# Utils:
uuid = { version= "1.8.0", features = ["serde"] }
rand = { version = "0.8.5", features = ["min_const_gen"] }
bcrypt = "0.15.1"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
slug = "0.1.5"
futures = "0.3.30"

[dev-dependencies]
sqlx-cli = "0.7.4"
cargo-watch = "8.5.2"
