[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Web Framework:
axum = { version = "0.7.4", features = ["http2"] }
axum-core = "0.4.3"
axum-extra = {version="0.9.2", features = ["cookie-private", "query", "cookie", "cookie-signed"]}

# Middleware:
tower = { version = "0.4.13", features = ["util", "timeout"] }
tower-http = { version = "0.5.1", features = ["cors", "fs", "trace"] }

# Database:
sqlx = { version = "0.7.3", features = ["runtime-tokio", "macros", "uuid", "json", "chrono", "migrate", "postgres"] }

# Async Runtime:
tokio = { version = "1.21.2", features = ["full"] }
tokio-postgres = "0.7.7"

# Logging:
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Metrics
axum-prometheus = "0.6.1"

# Errors:
thiserror = "1.0.37"
anyhow = "1.0.79"

# Environment variables:
envy = "0.4.2"

# Serialisation/Deserialisation:
serde = { version = "1.0.196", features = ["derive"] }

# Validation:
validator = { version = "0.16.1", features = ["derive"] }

# Utils:
uuid = { version= "1.7.0", features = ["serde"] }
rand = { version = "0.8.5", features = ["min_const_gen"] }
chrono = { version = "0.4.33", features = ["clock", "serde"] }
serde_json = "1.0.113"
bcrypt = "0.15.0"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
cargo-watch = "8.5.2"

[dev-dependencies]
sqlx-cli = "0.7.3"
cargo-watch = "8.5.2"
