CREATE TABLE Tags (
  id SERIAL NOT NULL PRIMARY KEY,
  label TEXT NOT NULL UNIQUE,
  article_count INTEGER NOT NULL DEFAULT 0,
  tag_status TagStatus NOT NULL DEFAULT 'WAITING',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now (),
  updated_at TIMESTAMPTZ
);

SELECT
  trigger_updated_at ('Tags');

CREATE TABLE Interests (
  user_id INTEGER NOT NULL REFERENCES Users (id) ON UPDATE CASCADE ON DELETE CASCADE,
  tag_id INTEGER NOT NULL REFERENCES Tags (id) ON UPDATE CASCADE ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now (),
  PRIMARY KEY (user_id, tag_id)
);

CREATE TABLE ArticleTags (
  article_id INTEGER REFERENCES Articles (id) ON UPDATE CASCADE ON DELETE CASCADE,
  tag_id INTEGER REFERENCES Tags (id) ON UPDATE CASCADE ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now (),
  PRIMARY KEY (article_id, tag_id)
);
