CREATE TYPE TagStatus AS ENUM ('APPROVED', 'BANNED', 'WAITING');

CREATE TABLE Tags (
  slug TEXT PRIMARY KEY,
  label TEXT UNIQUE NOT NULL,
  article_count INTEGER NOT NULL DEFAULT 0,
  tag_status TagStatus NOT NULL DEFAULT 'WAITING',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now (),
  updated_at TIMESTAMPTZ
);

SELECT
  trigger_updated_at ('Tags');

CREATE TABLE Interests (
  user_id TEXT NOT NULL REFERENCES Users (id) ON UPDATE CASCADE ON DELETE CASCADE,
  tag_slug TEXT NOT NULL REFERENCES Tags (slug) ON UPDATE CASCADE ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now (),
  PRIMARY KEY (user_id, tag_slug)
);

CREATE TABLE ArticleTags (
  article_id TEXT REFERENCES Articles (id) ON UPDATE CASCADE ON DELETE CASCADE,
  tag_slug TEXT NOT NULL REFERENCES Tags (slug) ON UPDATE CASCADE ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now (),
  PRIMARY KEY (article_id, tag_slug)
);
