CREATE TABLE Lists (
  id SERIAL NOT NULL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES Users (id) ON UPDATE CASCADE ON DELETE CASCADE,
  slug TEXT UNIQUE NOT NULL,
  label TEXT NOT NULL,
  image TEXT,
  visibility Visibility NOT NULL DEFAULT 'PRIVATE',
  article_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now (),
  updated_at TIMESTAMPTZ
);

SELECT
  trigger_updated_at ('Lists');

CREATE TABLE ListArticle (
  list_id INTEGER NOT NULL REFERENCES Lists (id) ON UPDATE CASCADE ON DELETE CASCADE,
  article_id INTEGER NOT NULL REFERENCES Articles (id) ON UPDATE CASCADE ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now (),
  PRIMARY KEY (list_id, article_id)
);
