import { EditorThemeClasses } from "lexical";

const editor_theme: EditorThemeClasses = {
  // blockCursor: '',
  // characterLimit: '',
  code: "relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-sm font-semibold",
  // codeHighlight: {
  //   atrule: '',
  //   attr: '',
  //   boolean: '',
  //   builtin: '',
  //   cdata: '',
  //   char: '',
  //   class: '',
  //   'class-name': '',
  //   comment: '',
  //   constant: '',
  //   deleted: '',
  //   doctype: '',
  //   entity: '',
  //   function: '',
  //   important: '',
  //   inserted: '',
  //   keyword: '',
  //   namespace: '',
  //   number: '',
  //   operator: '',
  //   prolog: '',
  //   property: '',
  //   punctuation: '',
  //   regex: '',
  //   selector: '',
  //   string: '',
  //   symbol: '',
  //   tag: '',
  //   url: '',
  //   variable: '',
  // },
  link: "cursor-pointer",
  embedBlock: {
    base: "select-none",
    focus: "outline-2",
  },
  // hashtag: '',
  heading: {
    h1: "text-4xl font-extrabold tracking-tight lg:text-5xl",
    h2: "border-b pb-2 text-3xl font-semibold tracking-tight first:mt-0",
    h3: "text-2xl font-semibold tracking-tight",
    h4: "text-xl font-semibold tracking-tight",
    h5: "",
    h6: "",
  },
  image: "editor-image",
  indent: "",
  // inlineImage: 'inline-editor-image',
  layoutContainer: "grid gap-3 my-3 mx-0",
  layoutItem: "border gap-3 py-2 px-4",
  list: {
    ol: "list-inside list-decimal",
    ul: "list-inside list-disc",
  },
  ltr: "text-left",
  // mark: '',
  // markOverlap: '',
  paragraph: "relative m-0",
  quote: "mt-6 border-l-2 pl-6 italic",
  rtl: "text-right",
  // table: '',
  // tableAddColumns: '',
  // tableAddRows: '',
  // tableCell: '',
  // tableCellActionButton: '',
  // tableCellActionButtonContainer: '',
  // tableCellEditing: '',
  // tableCellHeader: '',
  // tableCellPrimarySelected: '',
  // tableCellResizer: '',
  // tableCellSelected: '',
  // tableCellSortedIndicator: '',
  // tableResizeRuler: '',
  // tableSelected: '',
  // tableSelection: '',

  text: {
    bold: "font-bold",
    code: "font-mono",
    italic: "italic",
    strikethrough: "line-through",
    underline: "underline",
    underlineStrikethrough: "underlined-line-through",
  },
};

export default editor_theme;
