client:
  port: 4000
  host: "localhost"
  ssl: false

api_server:
  port: 5000
  host: "localhost"
  ssl: false

resource_server:
  port: 5001
  host: "localhost"
  ssl: false

auth_server:
  port: 5002
  host: "localhost"
  ssl: false

notification_server:
  port: 5003
  host: "localhost"
  ssl: false

storage_server:
  port: 5004
  host: "localhost"
  ssl: false

auth:
  secret: secret
  hmac_secret: ""
  google:
    client_id: client_id
    client_secret: client_secret
  github:
    client_id: client_id
    client_secret: client_secret

query:
  per_page: 25

cookies:
  salt: __Secure.orta
  theme: theme
  csrf_state:
    name: csrf_state_name
    duration: 5
  code_verfier:
    name: code_verfier_name
    duration: 5
  access_token:
    name: access_token
    duration: 5
  refresh_token:
    name: refresh_token
    duration: 43200
  fingerprint:
    name: fingerprint
    duration: 43200 # must be less ot equal to refresh token

database:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: password
  database_name: blog
  require_ssl: false

message_broker:
  port: 5672
  hostname: localhost
  username: mbuser
  password: mbpassword

storage:
  port: 9001
  hostname: localhost
  username: storage_username
  password: storage_password
  access_key: access_key
  secret_key: secret_key
  bucket_name: dev

mail:
  smtp_host: "smpt.gmail.com"
  smtp_port: 587
  smtp_user: smtp_user
  smtp_password: smtp_password
