api:
  port: 5000
  host: "localhost"

database:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: password
  database_name: blog
  require_ssl: false

auth:
  port: 5001
  secret: secret
  hmac_secret: ""
  google:
    client_id: client_id
    client_secret: client_secret
  github:
    client_id: client_id
    client_secret: client_secret

resource:
  port: 5002
  per_page: 25

cookies:
  salt: __Secure.orta
  theme: theme
  csrf_state:
    name: csrf_state_name
    duration: 5
  code_verfier:
    name: code_verfier_name
    duration: 5
  access_token:
    name: access_token
    duration: 5
  refresh_token:
    name: refresh_token
    duration: 43200
  fingerprint:
    name: fingerprint
    duration: 43200 # must be less ot equal to refresh token
# email_client:
#   base_url: "localhost"
#   sender_email: "test@gmail.com"
#   authorization_token: "my-secret-token"
#   timeout_milliseconds: 10000
# redis_uri: "redis://127.0.0.1:6379"
